// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Nav$ReactTemplate = require("./Nav.bs.js");
var Home$ReactTemplate = require("./Home.bs.js");
var Footer$ReactTemplate = require("./Footer.bs.js");
var Profile$ReactTemplate = require("./Profile.bs.js");
var Settings$ReactTemplate = require("./Settings.bs.js");

function mapUrlToRoute(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "create" : 
          if (match[1]) {
            return /* Home */Block.__(0, [/* array */[]]);
          } else {
            return /* Create */0;
          }
      case "edit" : 
          if (match[1]) {
            return /* Home */Block.__(0, [/* array */[]]);
          } else {
            return /* Edit */Block.__(1, ["asd"]);
          }
      case "profile" : 
          if (match[1]) {
            return /* Home */Block.__(0, [/* array */[]]);
          } else {
            return /* Profile */1;
          }
      case "settings" : 
          if (match[1]) {
            return /* Home */Block.__(0, [/* array */[]]);
          } else {
            return /* Settings */2;
          }
      default:
        return /* Home */Block.__(0, [/* array */[]]);
    }
  } else {
    return /* Home */Block.__(0, [/* array */["hello"]]);
  }
}

var $$default = ReasonReact.reducerComponent("App");

function make() {
  return /* record */[
          /* debugName */$$default[/* debugName */0],
          /* reactClassInternal */$$default[/* reactClassInternal */1],
          /* handedOffState */$$default[/* handedOffState */2],
          /* willReceiveProps */$$default[/* willReceiveProps */3],
          /* didMount */$$default[/* didMount */4],
          /* didUpdate */$$default[/* didUpdate */5],
          /* willUnmount */$$default[/* willUnmount */6],
          /* willUpdate */$$default[/* willUpdate */7],
          /* shouldUpdate */$$default[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* route */0];
              var tmp;
              if (typeof match === "number") {
                switch (match) {
                  case 0 : 
                      tmp = ReasonReact.element(/* None */0, /* None */0, Home$ReactTemplate.make(/* array */[]));
                      break;
                  case 1 : 
                      tmp = ReasonReact.element(/* None */0, /* None */0, Profile$ReactTemplate.make(/* array */[]));
                      break;
                  case 2 : 
                      tmp = ReasonReact.element(/* None */0, /* None */0, Settings$ReactTemplate.make(/* array */[]));
                      break;
                  
                }
              } else {
                tmp = match.tag ? ReasonReact.element(/* None */0, /* None */0, Home$ReactTemplate.make(/* array */[])) : ReasonReact.element(/* None */0, /* None */0, Home$ReactTemplate.make(/* array */[]));
              }
              return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Nav$ReactTemplate.make(/* array */[])), tmp, ReasonReact.element(/* None */0, /* None */0, Footer$ReactTemplate.make(/* array */[])));
            }),
          /* initialState */(function () {
              return /* record */[/* route : Home */Block.__(0, [/* array */[]])];
            }),
          /* retainedProps */$$default[/* retainedProps */11],
          /* reducer */(function (action, _) {
              return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
            }),
          /* subscriptions */(function (self) {
              return /* :: */[
                      /* Sub */[
                        (function () {
                            return ReasonReact.Router[/* watchUrl */1]((function (url) {
                                          console.log(url);
                                          return Curry._1(self[/* send */3], /* ChangeRoute */[mapUrlToRoute(url)]);
                                        }));
                          }),
                        ReasonReact.Router[/* unwatchUrl */2]
                      ],
                      /* [] */0
                    ];
            }),
          /* jsElementWrapped */$$default[/* jsElementWrapped */14]
        ];
}

exports.mapUrlToRoute = mapUrlToRoute;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.make = make;
/* default Not a pure module */
