// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var $$default = ReasonReact.statelessComponent("Article");

function make() {
  return /* record */[
          /* debugName */$$default[/* debugName */0],
          /* reactClassInternal */$$default[/* reactClassInternal */1],
          /* handedOffState */$$default[/* handedOffState */2],
          /* willReceiveProps */$$default[/* willReceiveProps */3],
          /* didMount */$$default[/* didMount */4],
          /* didUpdate */$$default[/* didUpdate */5],
          /* willUnmount */$$default[/* willUnmount */6],
          /* willUpdate */$$default[/* willUpdate */7],
          /* shouldUpdate */$$default[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "article-page"
                        }, React.createElement("div", {
                              className: "banner"
                            }, React.createElement("div", {
                                  className: "container"
                                }, React.createElement("h1", undefined, "How to build webapps that scale"), React.createElement("div", {
                                      className: "article-meta"
                                    }, React.createElement("a", {
                                          href: ""
                                        }, React.createElement("img", {
                                              src: "http://i.imgur.com/Qr71crq.jpg"
                                            })), React.createElement("div", {
                                          className: "info"
                                        }, React.createElement("a", {
                                              className: "author",
                                              href: ""
                                            }, "Eric Simons"), React.createElement("span", {
                                              className: "date"
                                            }, "January 20th")), React.createElement("button", {
                                          className: "btn btn-sm btn-outline-secondary"
                                        }, React.createElement("i", {
                                              className: "ion-plus-round"
                                            }), "Follow Eric Simons", React.createElement("span", {
                                              className: "counter"
                                            }, "(10)")), React.createElement("button", {
                                          className: "btn btn-sm btn-outline-primary"
                                        }, React.createElement("i", {
                                              className: "ion-heart"
                                            }), "Favorite Post", React.createElement("span", {
                                              className: "counter"
                                            }, "(29)"))))), React.createElement("div", {
                              className: "container page"
                            }, React.createElement("div", {
                                  className: "row article-content"
                                }, React.createElement("div", {
                                      className: "col-md-12"
                                    }, React.createElement("p", undefined, "Web development technologies have evolved at an incredible clip over the past few years."), React.createElement("h2", {
                                          id: "introducing-ionic"
                                        }, "Introducing RealWorld."), React.createElement("p", undefined, "It's a great solution for learning how other frameworks work."))), React.createElement("hr", undefined), React.createElement("div", {
                                  className: "article-actions"
                                }, React.createElement("div", {
                                      className: "article-meta"
                                    }, React.createElement("a", {
                                          href: "profile.html"
                                        }, React.createElement("img", {
                                              src: "http://i.imgur.com/Qr71crq.jpg"
                                            })), React.createElement("div", {
                                          className: "info"
                                        }, React.createElement("a", {
                                              className: "author",
                                              href: ""
                                            }, "Eric Simons"), React.createElement("span", {
                                              className: "date"
                                            }, "January 20th")), React.createElement("button", {
                                          className: "btn btn-sm btn-outline-secondary"
                                        }, React.createElement("i", {
                                              className: "ion-plus-round"
                                            }), "Follow Eric Simons", React.createElement("span", {
                                              className: "counter"
                                            }, "(10)")), React.createElement("button", {
                                          className: "btn btn-sm btn-outline-primary"
                                        }, React.createElement("i", {
                                              className: "ion-heart"
                                            }), "Favorite Post", React.createElement("span", {
                                              className: "counter"
                                            }, "(29)")))), React.createElement("div", {
                                  className: "row"
                                }, React.createElement("div", {
                                      className: "col-xs-12 col-md-8 offset-md-2"
                                    }, React.createElement("form", {
                                          className: "card comment-form"
                                        }, React.createElement("div", {
                                              className: "card-block"
                                            }, React.createElement("textarea", {
                                                  className: "form-control",
                                                  placeholder: "Write a comment...",
                                                  rows: 3
                                                })), React.createElement("div", {
                                              className: "card-footer"
                                            }, React.createElement("img", {
                                                  className: "comment-author-img",
                                                  src: "http://i.imgur.com/Qr71crq.jpg"
                                                }), React.createElement("button", {
                                                  className: "btn btn-sm btn-primary"
                                                }, "Post Comment"))), React.createElement("div", {
                                          className: "card"
                                        }, React.createElement("div", {
                                              className: "card-block"
                                            }, React.createElement("p", {
                                                  className: "card-text"
                                                }, "With supporting text below as a natural lead-in to additional content.")), React.createElement("div", {
                                              className: "card-footer"
                                            }, React.createElement("a", {
                                                  className: "comment-author",
                                                  href: ""
                                                }, React.createElement("img", {
                                                      className: "comment-author-img",
                                                      src: "http://i.imgur.com/Qr71crq.jpg"
                                                    })), React.createElement("a", {
                                                  className: "comment-author",
                                                  href: ""
                                                }, "Jacob Schmidt"), React.createElement("span", {
                                                  className: "date-posted"
                                                }, "Dec 29th"))), React.createElement("div", {
                                          className: "card"
                                        }, React.createElement("div", {
                                              className: "card-block"
                                            }, React.createElement("p", {
                                                  className: "card-text"
                                                }, "With supporting text below as a natural lead-in to additional content.")), React.createElement("div", {
                                              className: "card-footer"
                                            }, React.createElement("a", {
                                                  className: "comment-author",
                                                  href: ""
                                                }, React.createElement("img", {
                                                      className: "comment-author-img",
                                                      src: "http://i.imgur.com/Qr71crq.jpg"
                                                    })), React.createElement("a", {
                                                  className: "comment-author",
                                                  href: ""
                                                }, "Jacob Schmidt"), React.createElement("span", {
                                                  className: "date-posted"
                                                }, "Dec 29th"), React.createElement("span", {
                                                  className: "mod-options"
                                                }, React.createElement("i", {
                                                      className: "ion-edit"
                                                    }), React.createElement("i", {
                                                      className: "ion-trash-a"
                                                    }))))))));
            }),
          /* initialState */$$default[/* initialState */10],
          /* retainedProps */$$default[/* retainedProps */11],
          /* reducer */$$default[/* reducer */12],
          /* subscriptions */$$default[/* subscriptions */13],
          /* jsElementWrapped */$$default[/* jsElementWrapped */14]
        ];
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.make = make;
/* default Not a pure module */
