// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var $$default = ReasonReact.statelessComponent("CreateArticle");

function make() {
  return /* record */[
          /* debugName */$$default[/* debugName */0],
          /* reactClassInternal */$$default[/* reactClassInternal */1],
          /* handedOffState */$$default[/* handedOffState */2],
          /* willReceiveProps */$$default[/* willReceiveProps */3],
          /* didMount */$$default[/* didMount */4],
          /* didUpdate */$$default[/* didUpdate */5],
          /* willUnmount */$$default[/* willUnmount */6],
          /* willUpdate */$$default[/* willUpdate */7],
          /* shouldUpdate */$$default[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "editor-page"
                        }, React.createElement("div", {
                              className: "container page"
                            }, React.createElement("div", {
                                  className: "row"
                                }, React.createElement("div", {
                                      className: "col-md-10 offset-md-1 col-xs-12"
                                    }, React.createElement("form", undefined, React.createElement("fieldset", undefined, React.createElement("fieldset", {
                                                  className: "form-group"
                                                }, React.createElement("input", {
                                                      className: "form-control form-control-lg",
                                                      placeholder: "Article Title",
                                                      type: "text"
                                                    })), React.createElement("fieldset", {
                                                  className: "form-group"
                                                }, React.createElement("input", {
                                                      className: "form-control",
                                                      placeholder: "What's this article about?",
                                                      type: "text"
                                                    })), React.createElement("fieldset", {
                                                  className: "form-group"
                                                }, React.createElement("textarea", {
                                                      className: "form-control",
                                                      placeholder: "Write your article (in markdown)",
                                                      rows: 8
                                                    })), React.createElement("fieldset", {
                                                  className: "form-group"
                                                }, React.createElement("input", {
                                                      className: "form-control",
                                                      placeholder: "Enter tags",
                                                      type: "text"
                                                    }), React.createElement("div", {
                                                      className: "tag-list"
                                                    })), React.createElement("button", {
                                                  className: "btn btn-lg pull-xs-right btn-primary",
                                                  type: "button"
                                                }, "Publish Article")))))));
            }),
          /* initialState */$$default[/* initialState */10],
          /* retainedProps */$$default[/* retainedProps */11],
          /* reducer */$$default[/* reducer */12],
          /* subscriptions */$$default[/* subscriptions */13],
          /* jsElementWrapped */$$default[/* jsElementWrapped */14]
        ];
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.make = make;
/* default Not a pure module */
