// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Link$ReactTemplate = require("./Link.bs.js");

var component = ReasonReact.statelessComponent("Home");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "home-page"
                        }, React.createElement("div", {
                              className: "banner"
                            }, React.createElement("div", {
                                  className: "container"
                                }, React.createElement("h1", {
                                      className: "logo-font"
                                    }, "conduit"), React.createElement("p", undefined, "A place to share your knowledge."))), React.createElement("div", {
                              className: "container page"
                            }, React.createElement("div", {
                                  className: "row"
                                }, React.createElement("div", {
                                      className: "col-md-9"
                                    }, React.createElement("div", {
                                          className: "feed-toggle"
                                        }, React.createElement("ul", {
                                              className: "nav nav-pills outline-active"
                                            }, React.createElement("li", {
                                                  className: "nav-item"
                                                }, React.createElement("a", {
                                                      className: "nav-link disabled",
                                                      href: ""
                                                    }, "Your Feed")), React.createElement("li", {
                                                  className: "nav-item"
                                                }, React.createElement("a", {
                                                      className: "nav-link active",
                                                      href: ""
                                                    }, "Global Feed")))), React.createElement("div", {
                                          className: "article-preview"
                                        }, React.createElement("div", {
                                              className: "article-meta"
                                            }, React.createElement("a", {
                                                  href: "profile.html"
                                                }, React.createElement("img", {
                                                      src: "http://i.imgur.com/Qr71crq.jpg"
                                                    })), React.createElement("div", {
                                                  className: "info"
                                                }, React.createElement("a", {
                                                      className: "author",
                                                      href: ""
                                                    }, "Eric Simons"), React.createElement("span", {
                                                      className: "date"
                                                    }, "January 20th")), React.createElement("button", {
                                                  className: "btn btn-outline-primary btn-sm pull-xs-right"
                                                }, React.createElement("i", {
                                                      className: "ion-heart"
                                                    }), "29")), ReasonReact.element(/* None */0, /* None */0, Link$ReactTemplate.make("profile", "preview-link", /* array */[
                                                  React.createElement("h1", undefined, "How to build webapps that scale"),
                                                  React.createElement("p", undefined, "This is the description for the post."),
                                                  React.createElement("span", undefined, "Read more...")
                                                ])))), React.createElement("div", {
                                      className: "col-md-3"
                                    }, React.createElement("div", {
                                          className: "sidebar"
                                        }, React.createElement("p", undefined, "Popular Tags"), React.createElement("div", {
                                              className: "tag-list"
                                            }, React.createElement("a", {
                                                  className: "tag-pill tag-default",
                                                  href: ""
                                                }, "programming"), React.createElement("a", {
                                                  className: "tag-pill tag-default",
                                                  href: ""
                                                }, "javascript"), React.createElement("a", {
                                                  className: "tag-pill tag-default",
                                                  href: ""
                                                }, "emberjs")))))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
