// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Home$ReactTemplate = require("./Home.bs.js");

var $$default = ReasonReact.statelessComponent("Main");

function make() {
  return /* record */[
          /* debugName */$$default[/* debugName */0],
          /* reactClassInternal */$$default[/* reactClassInternal */1],
          /* handedOffState */$$default[/* handedOffState */2],
          /* willReceiveProps */$$default[/* willReceiveProps */3],
          /* didMount */$$default[/* didMount */4],
          /* didUpdate */$$default[/* didUpdate */5],
          /* willUnmount */$$default[/* willUnmount */6],
          /* willUpdate */$$default[/* willUpdate */7],
          /* shouldUpdate */$$default[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Home$ReactTemplate.make(/* array */[])));
            }),
          /* initialState */$$default[/* initialState */10],
          /* retainedProps */$$default[/* retainedProps */11],
          /* reducer */$$default[/* reducer */12],
          /* subscriptions */$$default[/* subscriptions */13],
          /* jsElementWrapped */$$default[/* jsElementWrapped */14]
        ];
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.make = make;
/* default Not a pure module */
